FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1-mesa-glx libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY ml/requirements.txt /tmp/ml_requirements.txt
COPY backend/requirements.txt /tmp/backend_requirements.txt

RUN pip install --no-cache-dir -r /tmp/ml_requirements.txt \
    -r /tmp/backend_requirements.txt \
    requests matplotlib

COPY . /app

EXPOSE 8000
